name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
      - 'feature/*'
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        if: github.ref == 'refs/heads/main'
        run: docker build -t ${{ secrets.DOCKER_REPO }}:latest .

      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: docker push ${{ secrets.DOCKER_REPO }}:latest

      - name: Deploy to EC2
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_REPO }}:latest
            sudo docker stop user-mgmt-container || true
            sudo docker rm user-mgmt-container || true
            sudo docker run -d --name user-mgmt-container -p 8081:8081 ${{ secrets.DOCKER_REPO }}:latest
