name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "dev", "staging", "feature/**" ]
  pull_request:
    branches: [ "main", "dev", "staging" ]

jobs:
  # 1️⃣ Run Tests
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Maven tests
        run: mvn clean test

      - name: Upload test reports
        if: always()   # ensures upload happens even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports/ 


  # 1️⃣ Build JAR with Maven
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/user-management-service-0.0.1-SNAPSHOT.jar

  # 2️⃣ Build & Push Docker image (only on staging & main)
  docker:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/main'
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: target/

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set Docker tag
        id: vars
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "TAG=latest" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" == "refs/heads/staging" ]]; then
            echo "TAG=staging" >> $GITHUB_ENV
          else
            echo "TAG=${GITHUB_SHA}" >> $GITHUB_ENV
          fi
          
      - name: Build Docker image
        run: |
           docker build -t ${{ secrets.DOCKER_REPO }}:${{ env.TAG }} .
           
      - name: Push Docker image
        run: |
           docker push ${{ secrets.DOCKER_REPO }}:${{ env.TAG }}
           

  # 3️⃣ Deploy to EC2 (only on main)
  deploy:
    needs: docker
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker stop user-mgmt-container || true
            docker rm user-mgmt-container || true
            docker pull ${{ secrets.DOCKER_REPO }}:latest
            docker run -d \
            --name user-mgmt-container \
            -p 8081:8081 \
            -e DB_URL=${{ github.ref == 'refs/heads/main' && secrets.PROD_DB_URL || secrets.STAGING_DB_URL }} \
            -e API_KEY=${{ github.ref == 'refs/heads/main' && secrets.PROD_API_KEY || secrets.STAGING_API_KEY }} \
            ${{ secrets.DOCKER_REPO }}:latest
